# Generated by Django 5.2.1 on 2025-05-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0002_user_disabled_at_user_managed_by_bio_avatar_dislike_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
